### ISSUE TITLE
sampling latent space before feeding to decoder

### ISSUE THREAD

**Issue by b-biswas** [b-biswas/MADNESS-legacy#2]
in the [model](https://github.com/b-biswas/FlowDeblender/blob/main/scripts/model.py) file, line 297. 
I am doing a z.sample()
Can it be avoided?

**Comment by b-biswas** [comment]
@junpenglao, in our last meeting we discussed a bit on this... 
My question here is that when I am building a decoder, I am able to directly feed z into the Keras model. From what I understood, the tpf.distribution variable is implicitly converted into an eager tensor by sampling when fed into the decoder. 
What I fail to understand is that when I repeat the same for the flow model, I get an error. And I need to explicitly call z.sample()

If I understand correctly, this won't really affect how the model works as the implicit and explicit conversions are the same operation. However, when I try to print model.summary()  the explicit call shows me a large number of layers which makes things hard to read.

**Comment by junpenglao** [comment]
Yes it is possible to not call `z.sample()`, by wrapping the output in a Keras layer. This is why I write a `class Flow(tfk.layers.Layer)` in https://github.com/b-biswas/FlowDeblender/blob/main/notebooks/VAE%2BFLOW.ipynb

**Comment by b-biswas** [comment]
Oh I see what you mean, I will update the flow model accordingly in a new PR
